<?php
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="row spec center-block">
            <div class="col-xs-12">
                <div class="col-md-3">
                    <?php if (empty($anime->imageUrl)): ?>
                        <img src="<?php echo $this->basePath('img/photo262.svg'); ?>" alt="<?php echo $anime->title; ?>" class="img-responsive"/>
                    <?php else: ?>
                        <img src="<?php echo $this->basePath($anime->imageUrl); ?>" alt="<?php echo $anime->title; ?>" class="img-responsive"/>
                    <?php endif ?>
                </div>
                <div class="col-md-9">
                    <h2 class="title-crop"><?php echo $this->escapeHtml($anime->title);?></h2>
                    <div id="synopsis"><p><?php echo $this->escapeHtml($anime->synopsis);?></p></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container col-md-12">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Anime Data</a></li>
        <li><a data-toggle="tab" href="#menu1">Add to list</a></li>
    </ul>
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h3>Anime Data</h3>
            <div class="row spec center-block">
                <div class="col-xs-4">Title</div>
                <div class="col-xs-8"><?php echo $this->escapeHtml($anime->title); ?></div>
            </div>
            <div class="row spec center-block">
                <div class="col-xs-4">Tags</div>
                <div class="col-xs-8"><?php echo $this->escapeHtml($anime->tags); ?></div>
            </div>
            <div class="row spec center-block">
                <div class="col-xs-4">Prequel</div>
                <div class="col-xs-8"><?php echo $this->escapeHtml($anime->prequel); ?></div>
            </div>
            <div class="row spec center-block">
                <div class="col-xs-4">Sequel</div>
                <div class="col-xs-8"><?php echo $this->escapeHtml($anime->sequel); ?></div>
            </div>
            <div class="row spec center-block">
                <div class="col-xs-4">Spinoff</div>
                <div class="col-xs-8"><?php echo $this->escapeHtml($anime->spinoff); ?></div>
            </div>
            <div class="row spec center-block">
                <div class="col-xs-4">Average rating</div>
                <div class="col-xs-8"><?php echo $this->escapeHtml($anime->avgRating); ?></div>
            </div>
            <div class="row spec center-block">
                <div class="col-xs-4">Episodes</div>
                <div class="col-xs-8"><?php echo $this->escapeHtml($anime->episodes); ?></div>
            </div>
        </div>
        <div id="menu1" class="tab-pane fade">
            <h3>Add anime</h3>
            <?php if ($this->error): ?>
                <p class="error">
                    <?php echo $this->error ?>
                </p>
            <?php endif ?>

            <section>
                <?php
                $form = $this->form;
                $form->prepare();
                $form->setAttribute('action', $this->url('anime', array('action' => 'addToList', 'id' => $anime->id, 'userId' => $user->id)));
                $form->setAttribute('method', 'post');
                echo $this->form()->openTag($form);
                ?>
                <dl class="zend_form">
                    <?php echo $this->formHidden($form->get('id')); ?>
                    <dd><?php
                        echo $this->formLabel($form->get('status'));
                        echo $this->formElement($form->get('status'));
                        echo $this->formElementErrors($form->get('status'));
                        ?></dd>

                    <dd><?php
                        echo $this->formLabel($form->get('rating'));
                        echo $this->formElement($form->get('rating'));
                        echo $this->formElementErrors($form->get('rating'));
                        ?></dd>

                    <dd><?php
                        echo $this->formLabel($form->get('episode'));
                        echo $this->formElement($form->get('episode'));
                        echo $this->formElementErrors($form->get('episode'));
                        ?></dd>

                    <dd><?php
                        echo $this->formElement($form->get('csrf'));
                        echo $this->formElementErrors($form->get('csrf'));
                        ?></dd></br>

                    <dd><?php
                        echo $this->formElement($form->get('submit'));
                        echo $this->formElementErrors($form->get('submit'));
                        ?></dd>

                </dl>
                <?php echo $this->form()->closeTag() ?>
            </section>
        </div>
    </div>
</div>


