<?php
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>

<div class="well">Recently Added</div>
    <div class="row spec center-block">
        <?php foreach ($animes as $anime) : ?>
            <div class="col-xs-6 col-md-3">
                <?php if (empty($anime->imageUrl)): ?>
                    <a href="<?php echo $this->url('anime',
                        array('action'=>'details', 'id' => $anime->id));?>" class="thumbnail">
                        <img src="<?php echo $this->basePath('img/photo262.svg'); ?>" alt="<?php echo $anime->title; ?>" class="img-rounded"/>
                        <p class="title-crop"><?php echo $this->escapeHtml($anime->title);?></p>
                    </a>
                <?php else: ?>
                    <a href="<?php echo $this->url('anime',
                        array('action'=>'details', 'id' => $anime->id));?>" class="thumbnail">
                        <img src="<?php echo $this->basePath($anime->imageUrl); ?>" alt="<?php echo $anime->title; ?>" class="img-rounded"/>
                        <p class="title-crop"><?php echo $this->escapeHtml($anime->title);?></p>
                    </a>
                <?php endif ?>
            </div>
        <?php endforeach; ?>
    </div>
