<?php
$this->headTitle('Admin Panel ');
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>
<h1>Welcome</h1>
<div>
    <h4><?php echo $this->escapeHtml($user->username); ?></h4>
    <hr />
    <a href="<?php echo $this->url('admin/manage-users',
        array('action' => 'index'));?>">Manage users</a>
    <br />
    <a href="<?php echo $this->url('admin/manage-animelist',
        array('action' => 'index'));?>">Manage anime list</a>
    <br />
    <a href="<?php echo $this->url('admin/messages',
        array('action' => 'index'));?>">Users messages</a>
</div>
<hr />