<h3>Edit your data</h3>

<?php if ($this->error): ?>
    <p class="error">
        <?php echo $this->error ?>
    </p>
<?php endif ?>

<section>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('user', array('action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <dl class="zend_form">
        <?php echo $this->formHidden($form->get('id')); ?>
        <?php echo $this->formHidden($form->get('isAdmin')); ?>
        <dd><?php
            echo $this->formElement($form->get('name'));
            echo $this->formElementErrors($form->get('name'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('surname'));
            echo $this->formElementErrors($form->get('surname'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('dob'));
            echo $this->formElementErrors($form->get('dob'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('location'));
            echo $this->formElementErrors($form->get('location'));
            ?></dd>
        <?php if (empty($user->avatarUrl)): ?>
            <img src="//placehold.it/200x200" class="img-thumbnail"/>
        <?php else: ?>
            <img src="<?php echo $this->basePath($user->avatarUrl); ?>"/>
        <?php endif ?>
        <dd><?php
            echo $this->formLabel($form->get('avatarUrl'));
            echo $this->formFile($form->get('avatarUrl'));
            echo $this->formElementErrors($form->get('avatarUrl'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('csrf'));
            echo $this->formElementErrors($form->get('csrf'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?></dd>

    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>