<?php

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>
<div class="panel panel-default">
    <div class="panel-heading"><h3><?php echo $this->escapeHtml($user->username); ?>'s Profile</h3></div>
    <div class="panel-body">
        <div class="col-xs-3">
            <?php if (empty($user->avatarUrl)): ?>
                <img src="//placehold.it/200x200" class="img-thumbnail"/>
            <?php else: ?>
                <img src="<?php echo $this->basePath($user->avatarUrl); ?>" class="img-thumbnail"/>
            <?php endif ?>
            <hr />
            <table class="table table-striped">
                <tbody>
                <?php foreach ($activity['infos'] as $info => $count): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($info); ?></td>
                    <td>&nbsp;</td>
                    <td><span class="badge"><?php echo $this->escapeHtml($count); ?></span></td>
                </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div class="col-xs-8">
            <div class="list-group">
                <a href="<?php echo $this->url('user',
                    array('action' => 'edit', 'id' => $user->id));?>" class="list-group-item">Edit your data</a>
                <a href="<?php echo $this->url('list', array('action' => 'anime', 'id' => $user->id));?>" class="list-group-item">Manage your list</a>
            </div>
            <?php if (!empty($activity['comments'])): ?>
            <h5 class="panel-title"><b>Your last comments</b></h5>
            <div class="list-group">
                <?php foreach ($activity['comments'] as $comment): ?>
                    <div class="list-group-item">
                        <blockquote>
                            <p><?php echo $this->escapeHtml($comment['body']); ?></p></p>
                            <small>in <cite><?php echo $this->escapeHtml($comment['title']); ?></cite></small>
                        </blockquote>
                    </div>
                <?php endforeach ?>
            </div>
            <?php endif ?>
        </div>
    </div>
</div>