<?php

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>
<div class="panel panel-default">
    <div class="panel-heading"><h3>Welcome</h3></div>
    <div class="panel-body">
        <div class="col-xs-2">
            <img src="<?php echo $this->basePath($user->avatarUrl); ?>" class="img-thumbnail"/>
            <h4>Hello, <?php echo $this->escapeHtml($user->username); ?></h4>
            <hr />
        </div>
        <div class="col-xs-10">
            <div class="list-group">
                <a href="<?php echo $this->url('user',
                    array('action' => 'edit', 'id' => $user->id));?>" class="list-group-item">Edit your data</a>
                <a href="<?php echo $this->url('list', array('action' => 'anime', 'id' => $user->id));?>" class="list-group-item">Manage your list</a>
            </div>
        </div>
    </div>
</div>