<?php

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>
<h1>Welcome</h1>
<div>
    <h4><?php echo $this->escapeHtml($user->username); ?></h4>
    <hr />
    <a href="<?php echo $this->url('user',
        array('action' => 'edit', 'id' => $user->id));?>">Edit your data</a>
</div>
<hr />