<?php
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>
<div class="panel panel-default">
    <div class="panel-heading"><h3>Admin Panel</h3></div>
    <div class="panel-body">
        <div class="col-xs-2">
            <?php if (empty($user->avatarUrl)): ?>
                <img src="//placehold.it/200x200" class="img-thumbnail"/>
            <?php else: ?>
                <img src="<?php echo $this->basePath($user->avatarUrl); ?>" class="img-thumbnail"/>
            <?php endif ?>
            <h4>Hello, <?php echo $this->escapeHtml($user->username); ?></h4>
        </div>
        <div class="col-xs-10">
            <div class="list-group">
                <a href="<?php echo $this->url('admin/manage-users',
                    array('action' => 'index'));?>" class="list-group-item">Manage users</a>
                <a href="<?php echo $this->url('admin/manage-anime',
                    array('action' => 'index'));?>" class="list-group-item">Manage anime list</a>
                <a href="<?php echo $this->url('support',
                    array('action' => 'mailbox', 'id' => $user->id));?>" class="list-group-item">Users messages</a>
            </div>
        </div>
    </div>
</div>
