<?php
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>
<div class="panel panel-default">
    <div class="panel-heading"><h3>Admin Panel</h3></div>
    <div class="panel-body">
        <div class="col-xs-3">
            <img src="<?php echo $this->basePath($user->avatarUrl); ?>" class="img-thumbnail"/>
            <h4>Hello, <?php echo $this->escapeHtml($user->username); ?></h4>
        </div>
        <div class="col-xs-9">
            <div class="btn-group-vertical">
                <a class="btn btn-default" role="button" href="<?php echo $this->url('admin/manage-users',
                        array('action' => 'index'));?>">Manage users</a>
                <a class="btn btn-default" role="button" href="<?php echo $this->url('admin/manage-anime',
                        array('action' => 'index'));?>">Manage anime list</a>
                <a class="btn btn-default" role="button" href="<?php echo $this->url('support',
                        array('action' => 'mailbox', 'id' => $user->id));?>">Users messages</a>
            </div>
        </div>
    </div>
</div>
