<?php

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>

<div class="well"><h1 class="title-crop"><?php echo $user->username;?> list</h1></div>
<div class="row spec center-block">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>&nbsp;</th>
                <th>Score</th>
                <th>Status</th>
                <th>Progress</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($animeList as $animeRow) : ?>
                    <tr>
                        <td><?php echo $animeRow->id; ?></td>
                        <td><?php echo $animeRow->title; ?></td>
                        <?php if ((!empty($loggedUser->id) && $loggedUser->id === $user->id)): ?>
                            <td>Edit/Delete</td>
                        <?php else: ?>
                            <td></td>
                        <?php endif ?>
                        <td><?php echo $animeRow->rating; ?></td>
                        <td><?php echo $animeRow->status; ?></td>
                        <td><?php echo $animeRow->episode . '/' . $animeRow->episodes; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<hr />