<?php

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>

<div class="well"><h1 class="title-crop"><?php echo $user->username;?> list</h1></div>
<div class="row spec center-block">
    <?php foreach ($animeList as $animeRow) : ?>
        <p><?php echo $animeRow->title . ' '; ?><?php echo 'episode: ' . $animeRow->episode; ?><?php echo '/' . $animeRow->episodes; ?></p>
    <?php endforeach; ?>
</div>
<hr />