<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('User Profile') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink()
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('System listy seriali') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('Home') ?></a></li>
                <?php if (!$this->user): ?>
                    <li><a href="<?php echo $this->url('login') ?>">&nbsp;<?php echo $this->translate('Login') ?></a></li>
                    <li><a href="<?php echo $this->url('register') ?>">&nbsp;<?php echo $this->translate('Sign-up') ?></a></li>
                <?php endif ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if ($this->user): ?>
                    <li><a>&nbsp;<?php echo $this->escapeHtml('Hello '.$user->username); ?></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span><span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="<?php echo $this->url('user') ?>">&nbsp;<?php echo $this->translate('Profile') ?></a></li>
                            <li class="divider"></li>
                            <?php if ($user->isAdmin): ?>
                                <li><a href="<?php echo $this->url('admin') ?>">&nbsp;<?php echo $this->translate('Admin panel') ?></a></li>
                                <li><a href="<?php echo $this->url('admin/manage-animelist') ?>">&nbsp;<?php echo $this->translate('Manage animes') ?></a></li>
                                <li class="divider"></li>
                            <?php endif ?>
                            <li><a href="<?php echo $this->url('logout') ?>">&nbsp;<?php echo $this->translate('Logout') ?></a></li>
                        </ul>
                    </li>
                <?php endif ?>
            </ul>
        </div><!--/.nav-collapse -->

    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; <?php echo date('Y') ?> by Stanisław Śledziona and Damian Gackowski</p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>