<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sSLS%s'), '<span class="zf-red">', '</span>') ?></h1>
        <p>Congratulations! You are the first one who can test our new application.</p>
        <p>Feel free to tell us what do you think about this site :)</p>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Check our anime DB') ?></h3>
            </div>
            <div class="panel-body">
                <p>In this thread, you'll find a comprehensive list of anime.</p>
                <p><a class="btn btn-success pull-right" href="/anime">Anime list &raquo;</a></p>
            </div>
        </div>
    </div>
</div>