<div class="container-fluid center-block">
    <div class="row">
        <img src="<?php echo $this->basePath('/img/banner.jpg'); ?>" class="img-responsive">
    </div>
</div>
<div class="row">
    <hr />
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">Check our anime DB</div>
            </div>
            <div class="panel-body text-center">
                <h3 class="">Custom Lists</h3>
                <p>Our system allow you to create a specific list for every anime you choose!!</p>
                <hr />
                <h3>Community</h3>
                <p>You can discuss with others using our comments system!</p>
                <p>If u want, you can also check list of your friend! Share your list using simple url!</p>
                <hr />
                <h3>Rate system</h3>
                <p>Rate your favorite animes!</p>
                <hr />
                <a href="/register" class="btn btn-default" role="button">Sign-up today</a>&nbsp;
                <a href="/login" class="btn btn-default" role="button">Login now</a>
            </div>
        </div>
    </div>
</div>