<h3>Edycja użytkownika</h3>

<?php if ($this->error): ?>
    <p class="error">
        <?php echo $this->error ?>
    </p>
<?php endif ?>

<section>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('admin/manage-users', array('action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <dl class="zend_form">
        <?php echo $this->formHidden($form->get('id')); ?>
        <dd><?php
            echo $this->formElement($form->get('name'));
            echo $this->formElementErrors($form->get('name'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('surname'));
            echo $this->formElementErrors($form->get('surname'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('dob'));
            echo $this->formElementErrors($form->get('dob'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('location'));
            echo $this->formElementErrors($form->get('location'));
            ?></dd>

        <dd><?php
            echo $this->formLabel($form->get('isAdmin'));
            ?>&nbsp;
            <?php
            echo $this->formElement($form->get('isAdmin'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('csrf'));
            echo $this->formElementErrors($form->get('csrf'));
            ?></dd>

        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?></dd>

    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>