<?php
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');
?>
<div>
    <table class="table">
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->username);?></td>
                <td><?php echo $this->escapeHtml($user->email);?></td>
                <td>
                    <?php if (($user->id === $admin->id)): ?>
                        <i>Cannot edit!</i>
                    <?php else: ?>
                        <a href="<?php echo $this->url('admin/manage-users',
                            array('action'=>'edit', 'id' => $user->id));?>">Edit</a> |
                    <?php endif ?>
                    <?php if (($user->id === $admin->id) || ($user->isAdmin)): ?>
                        <i>Cannot delete!</i>
                    <?php else: ?>
                        <a href="<?php echo $this->url('admin/manage-users',
                            array('action'=>'delete', 'id' => $user->id));?>" onclick="return confirm('Are you sure?')">Delete</a>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
