<?php
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');

$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function() {
 	$("a.ui-button").button();
  });', 'text/javascript');

?>
<div>
    <a href="<?php echo $this->url('admin/manage-anime', array('action' => 'create'));?>">Add new anime</a>
    <table class="table">
        <tr>
            <th>Title</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($animes as $anime) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($anime->title);?></td>
                <td>
                    <a href="<?php echo $this->url('admin/manage-anime',
                        array('action'=>'edit', 'id' => $anime->id));?>">Edit</a> |
                    <a href="<?php echo $this->url('admin/manage-anime',
                        array('action'=>'delete', 'id' => $anime->id));?>" onclick="return confirm('Are you sure?')">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
<?php
echo $this->paginationControl(
    $this->animes,
    'sliding',
    'partial/paginator.phtml',
    array(
        'route' => 'admin/manage-anime',
    )
);
?>